# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 812a2f79f8abacef8e290b8d6671f1fd3bed1fa72c17c98f1ce9ffacd56217808162d1a4a73e43251110e215e53e2189b60965bfff2021b61c5a3bbd98e5b1b0

test:
  secret_key_base: ef92adc818ff08c0f5b54f1c88a657fb1d60560583ebb8eabc8eedee264c0c3932c0ac25b4bb83343989602a2cee96e1653035853b67e155c070b178ff594360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
